name: "pre-criteria-assessment"
description: "Automatically passes or fails workflow based off a set of criteria"
inputs:
  non-impact-code:
    description: "Should the workflow automatically pass workflows or jobs with only non-impact code(like only documentation changes)?"
    required: false
    default: 'true'
  skip-duplicates:
    description: "Should the workflow automatically pass duplicate workflows or jobs?"
    required: false
    default: 'true'
outputs:
  skippable:
    description: "Whether or not the pre criteria assessment passes a workflow or job from running"
    value: "${{ env.skippable }}"

runs:
  using: "composite"
  steps:
    - name: Run non-impact-code analysis
      uses: ./.github/actions/non-impact-code
      id: non-impact-code
      if: ${{ inputs.non-impact-code == 'true' }}
      with:
        non-impact-files: |
          docs/**
          LICENSE
          README.md

    - name: Analyze any duplicate running actions
      uses: fkirc/skip-duplicate-actions@v5
      id: skip-duplicates
      if: ${{ inputs.skip-duplicates == 'true' }}
      with:
        cancel_others: "true"
        skip_after_successful_duplicate: "true"
        concurrent_skipping: "same_content_newer"

    - name: Assign the pre-criteria-assessment results
      id: assessment-status
      shell: bash
      run: |
        echo "skippable=${{ 
        ((inputs.non-impact-code == 'true') && (steps.non-impact-code.outputs.impactful)) 
        || 
        ((inputs.skip-duplicates == 'true') && (steps.skip-duplicates.outputs.should_skip)) 
        }}" >> $GITHUB_ENV
