# Automatically runs assessment and build livecd

name: automatic-build-livecd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:

permissions:
  actions: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre_assessment_check:
    runs-on: ubuntu-latest
    outputs:
      skippable: ${{ steps.pre-criteria-assessment.outputs.skippable }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run pre criteria assessment
        uses: ./.github/actions/pre-criteria-assessment

      - name: Assign pre criteria assessment status
        id: pre-criteria-assessment
        run: echo "skippable=${{ env.skippable }}" >> $GITHUB_OUTPUT

  # This workflow contains a single job called "build"
  automatic_build:
    needs: pre_assessment_check
    if: needs.pre_assessment_check.outputs.skippable != 'true'
    # The type of runner that the job will run on
    strategy:
      matrix:
        formats: [install-iso, virtualbox, proxmox-lxc, proxmox, linode, gce, docker, do]
    uses: ./.github/workflows/build-livecd.yml
    with:
      flake: ./#nixos-livecd
      format: ${{ matrix.formats }}

