run-name: Build a ${{ inputs.format }} livecd with ${{ inputs.configuration }}

on:
  workflow_call:
    inputs:
      configuration:  
        description: 'The path or filename of the nix configuration describing the image'
        type: string
        required: true
        default: 'configuration.nix'
      format:
        description: 'The nixOS image format'
        required: true
        type: string
        default: 'install-iso'

  workflow_dispatch:
    # TODO: Once input duplication is not needed anymore, refactor the input duplicate code.
    # See https://github.com/orgs/community/discussions/39357
    inputs:
      configuration:  
        description: 'The path or filename of the nix configuration describing the image'
        type: string
        required: true
        default: 'configuration.nix'
      format:
        description: 'The nixOS image format'
        required: true
        type: choice
        options:
          - info
          - warning
          - debug
          - amazon
          - azure
          - cloudstack
          - do
          - docker
          - gce
          - hyperv
          - install-iso
          - install-iso-hyperv
          - iso
          - kexec
          - kexec-bundle
          - kubevirt
          - linode
          - lxc
          - lxc-metadata
          - openstack
          - proxmox
          - proxmox-lxc
          - qcow
          - raw
          - raw-efi
          - sd-aarch64
          - sd-aarch64-installer
          - vagrant-virtualbox
          - virtualbox
          - vm
          - vm-bootloader
          - vm-nogui
          - vmware
        default: install-iso

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Generate NixOS Image
        uses: ./.github/actions/generate-nixos-image
        with:
          configuration: ${{ inputs.configuration }}
          format: ${{ inputs.format  }}
        id: generate-image

      - name: Assign Artifact filename
        run: |
          # Get short git hash from
          # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          filename=$(basename "${{ env.image-path }}")
          artifact_name=${{ inputs.format }}-${git_hash}-${filename}
          cd "$(dirname '${{ env.image-path }}')"
          #Move will require sudo permissions
          sudo mv "$filename" "$artifact_name"
          #Preserve nix store directory with hard link
          ln "$artifact_name" "$filename"
          echo "asset-path=$(readlink -f '$artifact_name')" >> $GITHUB_OUTPUT
          echo "artifact-name=$artifact_name" >> $GITHUB_ENV
        id: build-files

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact-name }}
          path: ${{ steps.build-files.outputs.asset-path }}
