# This is a basic workflow to help you get started with Actions

name: build-livecd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formats: [install-iso, proxmox-lxc]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache nix with
      # https://github.com/marketplace/actions/magic-nix-cache
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      # Runs a single command using the runners shell
      - name: Generate NixOS Image
        uses: .github/actions/generate-nixos-image
        configuration: configuration.nix
        format: ${{ matrix.formats }}
        id: generate-image

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.generate-image.outputs.image-path }}
