# Creates a release

run-name: Draft release tag ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag: 
        description: 'The release version/tag'
        type: string
        required: true
        default: 'default'
      formats:  
        description: "A list of livecd formats to release as an artifact, using ['a', 'b', 'c'] notation"
        type: string
        required: true
        default: "['install-iso', 'virtualbox', 'proxmox-lxc', 'proxmox', 'linode', 'gce', 'docker', 'do']"
      commitish:
        description: "Passthrough from action-gh-release: 'Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Defaults to repository default branch.'"
        required: false

permissions:
  contents: write

jobs:
  build_release:
    strategy:
      fail-fast: false
      matrix:
        formats: ${{ fromJSON(inputs.formats) }}
    uses: ./.github/workflows/build-livecd.yml
    with:
      configuration: configuration.nix
      format: ${{ matrix.formats }}
      commitish: ${{ inputs.commitish }}
  draft_release:
    needs: build_release
    if: always()
    runs-on: ubuntu-latest
    env:
      asset-path: ./assets
    steps:

      - name: Retrieve the build files
        uses: actions/download-artifact@v3
        id: build-files
        with:
          path: ${{ env.asset-path }}

      - name: Assign asset filenames
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          for file in ${{ env.asset-path }}; do
            mv -v "$file" "${file/$git_hash/${{ inputs.tag }}}"
          done

      - name: Create the release
        uses: softprops/action-gh-release@v1
        with: 
          files: ${{ env.asset-path }}/**
          tag_name: ${{ inputs.tag }}
          draft: true
          target_commitish: ${{ inputs.commitish }}
          generate_release_notes: true
          append_body: true
      

